---
version: 2
workflows:
  version: 2
  test:
    jobs:
      - format_check
      - validation_check

jobs:
  format_check:
    docker:
      - image: "hashicorp/terraform:0.12.13"
    steps:
      - checkout
      - run:
          name: Check terraform formatting
          command: terraform fmt -check=true -write=false -diff
  validation_check:
    working_directory: ~
    docker:
      - image: "hashicorp/terraform:0.12.13"
    steps:
      - checkout
      - run:
          name: create fake license file
          command: touch ~/fake.rli
      - run:
          name: create temporary certificate
          command: touch ~/temp.pfx
      - run:
          name: create fake tfvars file and provider stub
          command: echo -e "license_file = \"~/fake.rli\"\nresource_group_name = \"fake-rg\"\nvirtual_network_name = \"fake-vnet\"\nsubnet = \"fake-subnet\"\nkey_vault_name = \"fake-kv\"\ndomain = \"example.com\"\ntls_pfx_certificate = \"~/temp.pfx\"\ntls_pfx_certificate_password = \"fake-password\"" > terraform.tfvars
      - run:
          name: create provider stub
          command: echo -e "provider \"azurerm\" {\nversion= \"=1.44.0\"\nfeatures {}\n}\n" > provider.tf
      - run:
          name: init configs and check if valid
          command: terraform init && terraform validate
